tests/provider: Bulk update aws_availability_zones data sources in test configurations to exclude Local Zones (#12517)
* tests/provider: Bulk update aws_availability_zones data sources in test configurations to exclude Local Zones

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/12412

This is the least risky update for all testing to exclude Local Zones from the data source, since us-west-2-lax-1 generally is missing functionality and also to prevent Availability Zone and Local Zone mixing when multiple Availability Zones are required, which is not allowed in many services.

In the future, this type of configuration churn can be reduced with one of the following solutions:

- Removing aws_availability_zones data source usage where it has now been superceded by the creation of the aws_ec2_instance_type_offering data source
- Standardizing base configurations per data source/resource
- Standardizing shared configurations into helper test configurations and composing them

Output from acceptance testing (as a smoke test):

```
--- PASS: TestAccAWSLB_ALB_basic (197.43s)
```

* docs/provider: Include Local Zones filtering in Contributing Guide

Reference: https://github.com/terraform-providers/terraform-provider-aws/pull/12517#issuecomment-603784217

* data-source/aws_vpc_endpoint_service: Keep non-filtered aws_availability_zones data source configuration

Since the expected return value of availability_zones applies to all Availability Zones and Local Zones:

```
--- FAIL: TestAccDataSourceAwsVpcEndpointService_gateway (6.13s)
    testing.go:654: Step 0 error: Check failed: Check 3/10 error: data.aws_vpc_endpoint_service.test: Attribute 'availability_zones.#' expected "4", got "5"
```

Output from acceptance testing:

```
--- PASS: TestAccDataSourceAwsVpcEndpointService_gateway (15.03s)
```

* tests/data-source/aws_availability_zone: Exclude Local Zones from aws_availability_zones results in test configurations

Previously:

```
--- FAIL: TestAccDataSourceAwsAvailabilityZone_Filter (9.96s)
    testing.go:654: Step 0 error: Check failed: Check 1/7 error: data.aws_availability_zone.test: Attribute 'group_name' expected "us-west-2", got "us-west-2-lax-1"
```

Output from acceptance testing:

```
--- PASS: TestAccDataSourceAwsAvailabilityZone_Filter (16.70s)
--- PASS: TestAccDataSourceAwsAvailabilityZone_AllAvailabilityZones (16.97s)
--- PASS: TestAccDataSourceAwsAvailabilityZone_Name (17.17s)
--- PASS: TestAccDataSourceAwsAvailabilityZone_ZoneId (17.28s)
```